export const LOAD_OPEN_API_CONFIGURATION = 'LOAD_OPEN_API_CONFIGURATION'
export const LOAD_OPEN_API_CONFIGURATION_SUCCESS = 'LOAD_OPEN_API_CONFIGURATION_SUCCESS'
export const LOAD_OPEN_API_CONFIGURATION_ERROR = 'LOAD_OPEN_API_CONFIGURATION_ERROR'
export const SELECT_CURRENT_ENTITY = 'SELECT_CURRENT_ENTITY'